### ISSUE TITLE
RF05-El sistema debe mostrar un mapa centrado en la posición actual del usuario, sin importar si hay un usuario autentificado. 

### ISSUE THREAD

**Issue by flouMicaza** [DCC-CC4401/suTontoGrupo-T4#16]

**Comment by PabloReszczynski** [comment]
En el html original había un index.html que extendía base.html y tenía cierta funcionalidad del mapa. El problema es que ahora existen varias bases html y no puede ser que index extienda todas (o si?).

Puedo copiar y pegar el código de index en cada una de las bases, o hacer una nueva base y que las otras bases extiendan.
